def build(bld):
    # Define our new, clean 'modbus' module. It depends on the core
    # ns-3 libraries as well as the custom HELICS contrib module.
    module = bld.create_ns3_module('modbus',
                                   ['core', 'network', 'internet',
                                    'point-to-point', 'helics'])

    # Source files for the Modbus applications.
    module.source = [
        'model/modbus-master-app.cc',
        'model/modbus-slave-app.cc',
        'helper/modbus-helper.cc',
    ]

    # Header files that other modules can include.
    headers = bld(features='ns3header')
    headers.module = 'modbus'
    headers.source = [
        'model/modbus-master-app.h',
        'model/modbus-slave-app.h',
        'helper/modbus-helper.h',
    ]


