def build(bld):
    module = bld.create_ns3_module('modbus', ['core', 'network', 'internet', 'point-to-point', 'helics'])
    module.source = [
        'model/modbus-master-app.cc',
        'model/modbus-slave-app.cc',
        'helper/modbus-helper.cc',
    ]
    module.headers = [
        'model/modbus-master-app.h',
        'model/modbus-slave-app.h',
        'helper/modbus-helper.h',
    ]

